// Copyright 2004-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by entc, DO NOT EDIT.

package entglobalsearch_test

import (
	"context"
	"entgo.io/contrib/entglobalsearch/internal/example/ent/enttest"
	"entgo.io/contrib/entglobalsearch/internal/example/ent/user"
	"github.com/stretchr/testify/require"
	"testing"

	_ "github.com/mattn/go-sqlite3"
)

func TestGlobalSearch(t *testing.T) {
	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	defer client.Close()

	_, err := client.User.Query().All(context.Background())
	require.NoError(t, err)

	_, err = client.User.Query().Where(user.Username("ciaran")).All(context.Background())
	require.NoError(t, err)
}
